### ISSUE TITLE
The README is out of date

### ISSUE THREAD

**Issue by jlapeyre** [JuliaMolSim/JuLIP.jl#124]
The README talks only of Julia versions 0.5 and 0.6.

**Comment by cortner** [comment]
Good point. I’m doing this largely on my own And don’t have enough time to maintain it beyond what I need in my research. But I can at least try to keep the readme up to date. I’ll do that ASAP.

**Comment by cortner** [comment]
please check the new readme and reopen this issue if needed

**Comment by jlapeyre** [comment]
Looks great to me.
