### ISSUE TITLE
Add EAM potential for binary alloys

### ISSUE THREAD

**Issue by jamesgardner1421** [JuliaMolSim/JuLIP.jl#131]
I would like to implement the potential [described here](https://link.springer.com/article/10.1007/s00894-020-04588-x).

I have already obtained from the authors both the complete set of parameters for the analytical functions and also the LAMMPS input file in `.eam.alloy` format.

From what I understand, the code currently allows for single species potentials provided in the `.fs` format, but not `.eam.alloy`. So the simplest way to proceed would be to add a parser for this additional format and create a new type for binary alloys.

My plan would be:
1. Create a new type `EAM2 <: SitePotential`. This would have 3 pair potentials, 2 density functions, 2 embedding functions.
2. Add a constructor that creates the `EAM2` from the `.eam.alloy` file. This would be based on the existing `eam_from_fs` and `read_fs` functions.
3. Implement `evaluate!` and `evaluate_d!`, probably a few others too. I'm not sure how many of these functions are already provided but the existing `EAM1` appears to implement lots of them.

Points 1 and 2 should be simple enough, I can just follow the existing functions. The extra bit I have to figure out is how it identifies the different species.
Point 3 will likely be more challenging, some guidance here would be appreciated.

**Comment by jamesgardner1421** [comment]
Having now looked at ASE's implementation it looks like it might be better to create a generic `EAM` type that can work for arbitrary numbers of species. It could look something like:
```julia
struct EAM{T1, T2, T3, T4} <: SitePotential
	phi::Matrix{T1}
	rho::Vector{T2}
	F::Vector{T3}
	info::T4
end
```

**Comment by cortner** [comment]
Hi James - thanks for getting involved! yes I agree the second option is better. In fact I have a prototype somewhere in [emt](https://github.com/JuliaMolSim/JuLIP.jl/blob/f5340580337a64d35292b91286c96d20d5c172c0/src/emt.jl#L19)

not also that in ASE.jl one can parse an EAM file from which one could then extract the data, feed it into a Julia struct similar to EMT which would enable fast evaluations.

I would do that first and think about the parser later. There are several variants of EAM file formats and I’m not sure it is a good use of your or anybody’s  time to implement them all and fix all the little corner cases...

**Comment by cortner** [comment]
Please also take a look at the ZList and SZList to manage species
