### ISSUE TITLE
Error installing JuLIP from registry

### ISSUE THREAD

**Issue by jamesgardner1421** [JuliaMolSim/JuLIP.jl#136]
```julia
(@v1.5) pkg> add JuLIP
  Resolving package versions...
   Updating git-repo `https://github.com/JuliaMolSim/JuLIP.jl.git`
   Updating git-repo `https://github.com/libAtoms/JuLIP.jl.git`
ERROR: JuLIP: git object 78aa6bdc10bd50f3a53c7c833e0981f6a9f5c8a3 could not be found
```
I'm attempting to install JuLIP using the MolSim registry but am running into this error. Do you know what the problem is?

**Comment by cortner** [comment]
I have an idea. Ouch.

**Comment by cortner** [comment]
apologies for the delay. I shoudl be able to get to it this week. This is just to say that I haven't forgotten...

**Comment by cortner** [comment]
@jamesgardner1421 can't reproduce the problem. It is possible that I had forgotten to push a commit, but this is now done and that's why I can't reproduce. WOuld you mind checking again?

**Comment by jamesgardner1421** [comment]
Great thank you, it works now for me too. I think it was just missing the version commit so it couldn't find the version it was looking for. Thanks!
