### ISSUE TITLE
EAM Hessians Incorrect with PBC

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/JuLIP.jl#145]
how could that happen ?!?!?

**Comment by cortner** [comment]
notably, the pair potential and SW hessians are fine with PBC

**Comment by jameskermode** [comment]
So it’s not a neighbour list problem then?

**Comment by cortner** [comment]
was that our hypothesis until now? 

My sense is if the EAM energy is correct (I think we tested this) then the neighbourlist is fine. So it must be something else ... But I'm completely baffled what the problem could be.

**Comment by cortner** [comment]
In fact on JuLIP 0.8 it seems to be fine.

**Comment by jameskermode** [comment]
Related to spline package change? Can’t see how either given that the energy is correct.

**Comment by cortner** [comment]
I guess I'll have to bisect it

**Comment by cortner** [comment]
error occurs going from v0.10 to v0.11 -- i.e. James Gardner's implementation of multi-species EAM

**Comment by cortner** [comment]
it is bizarre: the only thing that has changed is the part that passes the test.

**Comment by cortner** [comment]
@jamesgardner1421  if you have any ideas at all?

**Comment by cortner** [comment]
Here is a little script that I've run through all minor versions of JULIP: 
```julia
using Test, JuLIP, StaticArrays, Printf, LinearAlgebra
using JuLIP.Potentials
using JuLIP.Testing
using JuLIP.Potentials: evaluate_d, evaluate_dd

test_pots = "/Users/ortner/.julia/datadeps/JuLIP_testpots/JuLIP_data/"
eam_Fe = JuLIP.Potentials.EAM(test_pots * "pfe.plt",
                              test_pots * "ffe.plt",
                              test_pots * "F_fe.plt")

at = bulk(:Fe, cubic=true) * 2
rattle!(at, 0.1)   # tests pass with 0.0!!

eam = eam_Fe
set_calculator!(at, eam)

set_pbc!(at, true)
@info("full finite-difference test ...")
@info(" ... EAM forces")
println(@test fdtest( x -> energy(at, x), x -> JuLIP.gradient(at, x), dofs(at) ))
@info(" ... EAM hessian")
println(@test fdtest_hessian( x->gradient(at, x), x->hessian(at, x), dofs(at) ))
```

**Comment by jamesgardner1421** [comment]
I'll take a look today to try to come up with something, nothing immediately stands out

**Comment by cortner** [comment]
Thank you - I completely missed that.

**Comment by cortner** [comment]
i've tagged a new version with the fix, thanks again James. I'm closing this but we can reopen a new issue on the ad problems.
