### ISSUE TITLE
site_energy_d gives back MethodError!

### ISSUE THREAD

**Issue by tinatorabi** [JuliaMolSim/JuLIP.jl#172]
I'm getting a MethodError when calling ```site_energy_d(superB::JuLIP.MLIPs.IPSuperBasis, at::AbstractAtoms, i0::Integer)```.

```
julia> site_energy_d(basis, Configs[1], 1)
ERROR: MethodError: no method matching evaluate_d!(::Matrix{SVector{3, Float64}}, ::NamedTuple{(:J, :tmp_J, :dJ, 
:tmpd_J), Tuple{SMatrix{1, 1, Vector{Float64}, 1}, SMatrix{1, 1, Nothing, 1}, SMatrix{1, 1, Vector{Float64}, 1}, SMatrix{1, 1, 
Nothing, 1}}}, ::PolyPairBasis{ACE1.OrthPolys.TransformedPolys{Float64, ACE1.Transforms.Agnesi2Transform{Float64, Int64}, ACE1.OrthPolys.OrthPolyBasis{Float64}, PolyEnvelope{Float64}}, 1}, ::SubArray{SVector{3, Float64}, 1, Vector{SVector{3, Float64}}, Tuple{UnitRange{Int64}}, true}, ::SubArray{AtomicNumber, 1, Vector{AtomicNumber}, Tuple{UnitRange{Int64}}, true}, ::AtomicNumber)
```

My JuLIP is v0.14.4.

**Comment by tinatorabi** [comment]
Yes, I need it for fitting to site entropy derivatives. here is the script:

```
using JuLIP, ASE, ACEpotentials
cu_bulk= bulk(:Cu, cubic=true, pbc=true) * 2
eam = JuLIP.Potentials.EAM("Cu.eam.alloy")

r0 = 2.55
basis = ACE1x.ace_basis(elements = [:Cu],
                  order = 3,
                  totaldegree = 10, 
                  rcut = 5.506786, 
                  r0 = r0,)
se= site_energy_d(basis, cu_bulk,1)
```
EAM potential file: [https://www.ctcms.nist.gov/potentials/Download/2001--Mishin-Y-Mehl-M-J-Papaconstantopoulos-D-A-et-al--Cu-1/2/Cu01.eam.alloy](url)

```
(@v1.9) pkg> status
Status `~/.julia/environments/v1.9/Project.toml`
  [8c4e8d19] ACE1pack v0.5.0
  [3b96b61c] ACEpotentials v0.6.3
  [51974c44] ASE v0.5.4
  [7d9fca2a] Arpack v0.5.4
  [6e4b80f9] BenchmarkTools v1.3.2
  [a93c6f00] DataFrames v1.6.1
  [31c24e10] Distributions v0.25.100
  [b305315f] Elliptic v1.0.1
  [6a86dc24] FiniteDiff v2.21.1
  [f6369f11] ForwardDiff v0.10.36
  [38e38edf] GLM v1.9.0
  [7073ff75] IJulia v1.24.2
  [945c410c] JuLIP v0.14.4
  [b964fa9f] LaTeXStrings v1.3.0
  [10e44e05] MATLAB v0.8.4
  [6f286f6a] MultivariateStats v0.10.2
  [2fcf5ba9] NeighbourLists v0.5.5
  [429524aa] Optim v1.7.7
  [91a5bcdd] Plots v1.39.0
  [438e738f] PyCall v1.96.1
  [d330b81b] PyPlot v2.11.2
  [37e2e3b7] ReverseDiff v1.15.1
  [47a9eef4] SparseDiffTools v2.6.0
  [684fba80] SparsityDetection v0.3.4
  [90137ffa] StaticArrays v1.6.3
  [0c5d862f] Symbolics v5.5.3
  ```

**Comment by cortner** [comment]
It seems there were multiple potential bugs but not too much trouble to fix them. 

@tinetorabi - can you please update your environment and make sure the you have JuLIP@0.14.5 and ACE1@0.11.16 and then try again? If it works, then you can close this issue. 

One comment : using `site_energy` and `site_energy_d` is actually an extremely inefficient way of fitting to per/atom quantities. Your code will spend about 99% of its time in allocating memory and then garbage-collecting it. No harm to try, but don't be surprised if it's slow. I will then show you in our next meeting how to do this "correctly".

**Comment by cortner** [comment]
It seems there were multiple potential bugs but not too much trouble to fix them. 

@tinetorabi - can you please update your environment and make sure the you have JuLIP@0.14.5 and ACE1@0.11.16 and then try again? If it works, then you can close this issue. 

One comment : using `site_energy` and `site_energy_d` is actually an extremely inefficient way of fitting to per/atom quantities. Your code will spend about 99% of its time in allocating memory and then garbage-collecting it. No harm to try, but don't be surprised if it's slow. I will then show you in our next meeting how to do this "correctly".
